languange: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t duonglh2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true duonglh2/docker-react npm run test -- --coverage
